### PR TITLE
CXXCBC-905: compress KV values over couchbase2

### PR DESCRIPTION
**Pull request by avsej**
The couchbase2 KV path neither requested nor produced snappy-compressed content and read only the
uncompressed field, so a compressed response would have decoded to an empty value (silent data
loss) and large values were always sent raw. RFC 77 makes compression default-on, matching the
Java/Go/.NET SDKs.

Thread the cluster compression settings into the converter: send COMPRESSION_ENABLED_OPTIONAL on
every read that can carry a document body unless the user disabled compression, snappy-compress
Upsert/Insert/Replace when the value is at least min_size and shrinks to at most min_ratio of its
original, and snappy-decode a content_compressed response. COMPRESSION_ENABLED_ALWAYS is never
sent.

A payload that does not decode, or that declares more than the transport's maximum message size,
fails the operation rather than yielding a value. Empty bytes with a valid CAS are
indistinguishable from an empty document, and sizing an allocation from an unvalidated length
header is a denial of service the process cannot survive.

---
Stacked PR **25/30** in the CNG (`couchbase2://`) transport series. The change specific to this PR is its top commit; the commits beneath it belong to earlier PRs in the series. Depends on #1046 — merge the series bottom-up.

### CODE REVIEW

File: test/cng/protostellar/live_kv.cxx [hunk 1]
```diff
@@ -0,0 +1,308 @@
...
+  credentials.password = env_or("TEST_CB2_PASSWORD", "password");
+
+  const auto bucket = env_or("TEST_CB2_BUCKET", "default");
+  const auto id = document_id{ bucket, "_default", "_default", "cng-live-kv-key" };
+  const std::string document = "{\"cng\":true}";
+
+  asio::io_context io;
+  auto work = asio::make_work_guard(io);
+  auto channel = ps::make_channel(endpoint, options, credentials);
+  component comp{ io, channel, credentials, 20000ms };
```
Comment (avsej) [inline test/cng/protostellar/live_kv.cxx]: **Build blocker.** The fifth required parameter `kv::compression_settings compression` is added to `component::component`, and this call site (also `:183`) still passes four arguments. With `CB_COUCHBASE2=1`, `cng_live_kv_test` fails to compile:

```
test/cng/protostellar/live_kv.cxx:100:53: error: no matching function for call to
  'component::component(<brace-enclosed initializer list>)'
core/protostellar/component.hxx:164:3: note: candidate expects 5 arguments, 4 provided
```

For accuracy: this is the third commit to break the same untouched call site. It was written in #1032/#1033; #1036 added a fifth parameter, #1038 replaced the timeouts with the `component_timeouts` aggregate so `20000ms` stopped converting even at arity four, and this commit adds a fifth again. The `build` check passes on #1034/#1035 and fails from #1036 upward on every platform leg — twelve consecutive pull requests.

Immediate fix at both sites (C++17, so no designated initialisers):

```suggestion
  component comp{ io, channel, credentials, component_timeouts{ 20000ms, 20000ms }, {} };
```

The durable fix is on the constructor: five positional parameters with no defaults make every addition a silent breaking change, and the first call site to break is in a test only a feature-gated build compiles. A `component_config` struct with named fields removes the class of failure.

File: core/protostellar/kv_converter.hxx [hunk 2]
```diff
@@ -0,0 +1,561 @@
...
+  }
+}
+
+// Reads a response's content oneof, snappy-decoding a compressed payload. A valid compressed
+// payload always decodes back to its original bytes (never an empty-but-successful value -- the
+// pre-fix silent-data-loss trap); only malformed snappy from the trusted gateway falls back to
+// empty.
+template<typename Proto>
+inline auto
+decode_content(const Proto& proto) -> std::vector<std::byte>
```
Comment (avsej) [inline core/protostellar/kv_converter.hxx]: **Blocker: a decode failure becomes an empty document with a success status.**

When the compressed arm is active and `snappy::Uncompress` fails, this returns an empty vector, the error context is untouched, and the caller sees success with a valid CAS, correct flags and no value. That is the silent-data-loss shape this commit exists to remove, reintroduced on the error path.

Read-modify-write scenario: `get` returns an empty value with success on a corrupted payload, the application mutates that nothing, and `replace` succeeds because the CAS is still valid — the original document is gone, with no error at any point.

Make the failure representable:

```cpp
template<typename Proto>
inline auto
decode_content(const Proto& proto) -> std::optional<std::vector<std::byte>>
{
  if (proto.has_content_compressed()) {
    auto uncompressed = snappy_uncompress(proto.content_compressed());
    if (!uncompressed) {
      return std::nullopt;
    }
    return to_bytes(*uncompressed);
  }
  return to_bytes(proto.content_uncompressed());
}
```

and have each of the three `decode` overloads set `ctx.ec` (`errc::network::protocol_error`) on `std::nullopt`. This is the convention `can_encode` already applies on the request side.

Related: `get_projected` is the one read path not converted here — it neither calls the read-compression helper nor uses `decode_content`. Since `GetRequest.compression` is `optional` with `COMPRESSION_ENABLED_OPTIONAL` as its zero value, a gateway using the plain value getter may compress that response anyway. gocb sets `Project` and `Compression` on the same request and decompresses unconditionally (`kvprovider_ps.go:491-497`).

File: core/protostellar/kv_converter.cxx [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+    return compressed;
+  }
+  return std::nullopt;
+}
+
+auto
+snappy_uncompress(const std::string& compressed) -> std::optional<std::string>
+{
+  std::string uncompressed;
+  if (snappy::Uncompress(compressed.data(), compressed.size(), &uncompressed)) {
```
Comment (avsej) [inline core/protostellar/kv_converter.cxx:65]: `snappy::Uncompress` resizes its output to the length varint in the payload header **before** validating the body, so a few bytes can declare a multi-gigabyte uncompressed length and cause an allocation of that size. The resulting `std::bad_alloc` is thrown inside an Asio completion handler and terminates the process rather than failing the operation.

The threat model — a buggy or compromised gateway — is one a client library should defend against. `snappy::GetUncompressedLength` reads the header without allocating:

```cpp
  std::size_t length{};
  if (!snappy::GetUncompressedLength(compressed.data(), compressed.size(), &length)) {
    return std::nullopt;
  }
  // The channel already caps messages at 25 MiB (RFC 77); an uncompressed value cannot
  // legitimately exceed the maximum document size either.
  if (length > max_uncompressed_value_size) {
    return std::nullopt;
  }
```

**Review by avsej — COMMENTED** [review]
## Review — PR #1047 (`CXXCBC-905`)

This commit adds Snappy compression for KV values over couchbase2: `COMPRESSION_ENABLED_OPTIONAL` on the read
requests, `content_compressed` on the write requests, and a `decode_content` helper that handles the response
oneof. The thresholds match the reference implementations exactly — 32 bytes and a 0.83 ratio, the same values as
couchbase-jvm-clients `CompressionConfig.DEFAULT_MIN_SIZE`/`DEFAULT_MIN_RATIO` and gocb's compressor — and
`COMPRESSION_ENABLED_ALWAYS` is correctly never sent. RFC 77's Compression section is the part of the
specification all three shipping SDKs agree on, and this implementation lands on the same side of it.

Two things block it: the commit does not compile, and the error path it adds destroys data silently.

### Strengths

- The read/write split matches RFC 77 exactly: `COMPRESSION_ENABLED_OPTIONAL` on `GetRequest`,
  `GetAndLockRequest` and `GetAndTouchRequest`, `content_compressed` on `InsertRequest`, `UpsertRequest` and
  `ReplaceRequest`, and the field left entirely unset when the user has disabled compression.
- Both the size and ratio thresholds are honoured, with the same defaults as couchbase-jvm-clients and gocb.
  Honouring only `min_size` is a common shortcut and it was not taken here.
- `decode_content` centralises the response-side oneof handling, which is what makes the remaining gap a
  one-place fix rather than a per-operation one.

### Findings

| # | Severity | Area | Finding | Location |
|---|---|---|---|---|
| 1 | blocker | build | A fifth required constructor parameter is added without updating two existing call sites | `test/cng/protostellar/live_kv.cxx:100` |
| 2 | blocker | correctness | A malformed compressed payload decodes to an empty document with a success status | `core/protostellar/kv_converter.hxx:191` |
| 3 | high | security | Decompression is unbounded: the declared length is allocated before the payload is validated | `core/protostellar/kv_converter.cxx:50` |
| 4 | medium | correctness | `get_projected` neither negotiates compression nor decodes it | `core/protostellar/kv_converter.hxx:191` |

#### 1. A fifth required constructor parameter without updating two call sites (blocker)

```cpp
component comp{ io, channel, credentials, 20000ms };
```

`component::component` gains a fifth required parameter, `kv::compression_settings compression`, and
`test/cng/protostellar/live_kv.cxx:100` and `:183` still pass four arguments. With `CB_COUCHBASE2=1` — which is
what CI uses — `cng_live_kv_test` fails to compile:

```
test/cng/protostellar/live_kv.cxx:100:53: error: no matching function for call to
  'couchbase::core::protostellar::component::component(<brace-enclosed initializer list>)'
core/protostellar/component.hxx:164:3: note: candidate expects 5 arguments, 4 provided
```

Worth being precise about the history, because it is not solely this commit's regression. That call site was
written in #1032/#1033 and has never been touched, while the constructor changed under it three times: #1036
added a fifth parameter, #1038 replaced the timeout parameters with the `component_timeouts` aggregate — at
which point `20000ms` stopped converting even though the arity was back to four — and this commit adds a fifth
parameter again. The `build` check passes on #1034 and #1035 and fails on #1036 and every pull request above it,
on every platform leg. So the series has been red for twelve consecutive pull requests, and this commit is the
third cause rather than the first.

The immediate fix is at both call sites (C++17, so no designated initialisers):

```cpp
component comp{ io, channel, credentials, component_timeouts{ 20000ms, 20000ms }, {} };
```

The design fix matters more. A five-parameter positional constructor with no defaults makes every added
parameter a silent breaking change to every call site, and the one call site that breaks first is in a test that
only a feature-gated build compiles. A configuration struct removes the whole class:

```cpp
struct component_config {
  std::shared_ptr<grpc::Channel> channel;
  cluster_credentials credentials;
  component_timeouts timeouts{};
  kv::compression_settings compression{};
};

component(asio::io_context& io, component_config config);
```

(inline comment on `test/cng/protostellar/live_kv.cxx:100`)

#### 2. A malformed compressed payload decodes to an empty document with success (blocker)

```cpp
decode_content(const Proto& proto) -> std::vector<std::byte>
```

When the compressed arm of the oneof is active and `snappy::Uncompress` fails, the helper returns an empty
vector and the caller has no way to distinguish that from a genuinely empty document. The error context is not
touched, so the response reports success with a valid CAS, correct flags, and no value.

This is the same failure mode the commit exists to remove — the header comment even describes the previous
behaviour as a silent-data-loss trap — reintroduced on the error path rather than the unsupported-feature path.

Failure scenario, read-modify-write: an application does `get`, mutates the returned document, and `replace`s it
with the original CAS. A corrupted or truncated compressed payload from the gateway yields an empty value with
success, the application applies its mutation to nothing, and the `replace` succeeds because the CAS is still
valid. The stored document is now whatever the mutation produces from an empty input, and the original content is
gone. No error is reported at any point.

The helper needs to be able to fail:

```cpp
template<typename Proto>
inline auto
decode_content(const Proto& proto) -> std::optional<std::vector<std::byte>>
{
  if (proto.has_content_compressed()) {
    auto uncompressed = snappy_uncompress(proto.content_compressed());
    if (!uncompressed) {
      return std::nullopt;      // caller sets ctx.ec
    }
    return to_bytes(*uncompressed);
  }
  return to_bytes(proto.content_uncompressed());
}
```

with each of the three `decode` overloads setting the context error — `errc::network::protocol_error` or
`errc::common::internal_server_failure` — when it gets `std::nullopt`. Failing closed here matches the
convention `can_encode` already applies on the request side.

(inline comment on `core/protostellar/kv_converter.hxx:191`)

#### 3. Decompression is unbounded (high)

```cpp
if (snappy::Uncompress(compressed.data(), compressed.size(), &uncompressed)) {
```

`snappy::Uncompress` resizes its output to the length varint in the payload header before validating the body, so
a small response can declare a very large uncompressed length and cause an allocation of that size. A handful of
bytes can request several gigabytes. The resulting `std::bad_alloc` is thrown inside an Asio completion handler,
which is a `noexcept` context in this codebase's handler chain, so the process terminates rather than the
operation failing.

The threat model here is a buggy or compromised gateway, which is worth defending against for a client library.
`snappy::GetUncompressedLength` reads the header without allocating, so the bound can be checked first:

```cpp
auto
snappy_uncompress(const std::string& compressed) -> std::optional<std::string>
{
  std::size_t length{};
  if (!snappy::GetUncompressedLength(compressed.data(), compressed.size(), &length)) {
    return std::nullopt;
  }
  // The channel already refuses messages above 25 MiB (RFC 77); an uncompressed value cannot
  // legitimately exceed the maximum document size either.
  if (length > max_uncompressed_value_size) {
    return std::nullopt;
  }
  std::string uncompressed;
  if (!snappy::Uncompress(compressed.data(), compressed.size(), &uncompressed)) {
    return std::nullopt;
  }
  return uncompressed;
}
```

(inline comment on `core/protostellar/kv_converter.cxx:50`)

#### 4. `get_projected` neither negotiates compression nor decodes it (medium)

`encode(get_projected_request)` does not call the read-compression helper that `encode(get_request)` uses, and
the corresponding decode still reads `content_uncompressed` directly rather than going through `decode_content`.
`get_projected` is the one read path in the file that this commit did not convert.

That matters because `GetRequest.compression` is `optional CompressionEnabled` whose zero value is
`COMPRESSION_ENABLED_OPTIONAL`, so a gateway reading it with the plain value getter rather than a presence check
sees `OPTIONAL` for an unset field and may return `content_compressed` anyway. The projected read then produces an
empty value with a success status — finding 2, on a path that has not even opted in. gocb sets `Project` and
`Compression` on the same `GetRequest` and decompresses unconditionally (`kvprovider_ps.go:491-497`);
couchbase-jvm-clients routes every Get response through the same `convertContent` (`CoreProtostellarKeyValueResponses.java:111-123`).

### Verdict

Blocked. The commit does not compile, and finding 2 turns a transport-level decode failure into silent data loss
on a read-modify-write cycle — which is the specific outcome this commit's own comment says it exists to remove.

File: test/cng/protostellar/live_kv.cxx (hunk 1 above)
Comment (avsej) [reply test/cng/protostellar/live_kv.cxx]: This does not hold against the current head. The constructor is already `component(asio::io_context&, component_config)`, `component_config` already carries `compression` as a named field, and both call sites already assign by name rather than positionally:

```cpp
component_config config;
config.channel = channel;
config.credentials = credentials;
config.timeouts = { 20000ms };
component comp{ io, config };
```

So the design fix asked for here is the one in place. No change was made.

The class of failure it removes did fire again, though, one level up: the couchbase2 cluster built `component_config` with three initialisers for its four fields, so `compression` silently took the struct's own default and `cluster_options.enable_compression` never reached the transport. That is fixed by a named helper beside `make_component_timeouts`.

File: core/protostellar/kv_converter.hxx (hunk 2 above)
Comment (avsej) [reply core/protostellar/kv_converter.hxx]: Already addressed at the current head, in the shape proposed: `decode_content` returns `std::optional<std::vector<std::byte>>` and each decoder reports `errc::common::internal_server_failure` on `std::nullopt` rather than handing back a value. The read-modify-write framing is now the stated reason in the code comment and the commit message, and a mutation returning an empty vector instead of `std::nullopt` is killed by `malformed_compressed_content_fails_closed`.

The related point is taken and `get_projected` now negotiates compression and decodes through `decode_content` like every other read, with the `feature_not_available` refusal removed from both the converter and the component.

The mechanism given for it does not hold, though. The reference gateway takes `compression` as a pointer and branches on presence, not on its value:

```go
	if compressMode != nil {
		switch *compressMode {
		case kv_v1.CompressionEnabled_COMPRESSION_ENABLED_OPTIONAL:
```

With the field unset it takes the `else` branch and uncompresses before replying, so an unset field was not read as `OPTIONAL`. What justifies the change is the citation: projections and compression travel on one `GetRequest`, and gocb, the Java SDK and the .NET SDK all set them together. Refusing a compressed answer outright made this the one read the client could not complete.

File: core/protostellar/kv_converter.cxx (hunk 3 above)
Comment (avsej) [reply core/protostellar/kv_converter.cxx:65]: Fixed as suggested. `snappy_uncompress` now reads the declared length with `snappy::GetUncompressedLength`, which does not allocate, and refuses anything above the transport's maximum message size before inflating.

The bound is the 25 MiB receive limit RFC 77 requires. It was a bare literal in `default_channel_arguments()` and is now the named `max_receive_message_size` that both sites share: a second copy of the number would drift from the limit it is meant to express.

`an_oversized_declared_length_is_refused` covers it, built from a *valid* frame just over the cap rather than a crafted header — a malformed header is refused with or without the bound, so that assertion would have passed for the wrong reason. The matching mutation raises the bound out of reach and is killed.

**Comment by avsej** [comment]
## Response — PR #1047 (`CXXCBC-905`)

Every point is answered below. Two of the four findings were already addressed at the head the review names and are reported as such rather than claimed as new work; the other two are fixed here, together with two defects found while checking them.

### 1. A fifth required constructor parameter without updating two call sites

> `component::component` gains a fifth required parameter, `kv::compression_settings compression`, and `test/cng/protostellar/live_kv.cxx:100` and `:183` still pass four arguments.

> The design fix matters more. A five-parameter positional constructor with no defaults makes every added parameter a silent breaking change to every call site […] A configuration struct removes the whole class

This does not hold against the current head. The constructor is already `component(asio::io_context&, component_config)`, `component_config` already carries `compression` as a named field, and both call sites already assign by name:

```cpp
component_config config;
config.channel = channel;
config.credentials = credentials;
config.timeouts = { 20000ms };
component comp{ io, config };
```

The suggested design is the one in place, arrived at for the reason given. No change was needed.

### 2. A malformed compressed payload decodes to an empty document with success

> When the compressed arm of the oneof is active and `snappy::Uncompress` fails, the helper returns an empty vector and the caller has no way to distinguish that from a genuinely empty document.

> The helper needs to be able to fail

Also already addressed at the current head, in the shape proposed: `decode_content` returns `std::optional<std::vector<std::byte>>`, and each decoder reports `errc::common::internal_server_failure` on `std::nullopt` rather than handing back a value.

The read-modify-write scenario is the right way to frame the severity, and it is now the stated reason in both the code comment and the commit message. A negative control was added for it: a mutation returning an empty vector instead of `std::nullopt` is killed by `malformed_compressed_content_fails_closed`.

### 3. Decompression is unbounded

> `snappy::Uncompress` resizes its output to the length varint in the payload header before validating the body, so a small response can declare a very large uncompressed length and cause an allocation of that size.

Fixed. `snappy_uncompress` now reads the declared length with `snappy::GetUncompressedLength`, which does not allocate, and refuses anything above the transport's maximum message size before inflating:

```cpp
std::size_t length{};
if (!snappy::GetUncompressedLength(compressed.data(), compressed.size(), &length)) {
  return std::nullopt;
}
if (length > max_receive_message_size) {
  return std::nullopt;
}
```

The consequence given for the throw was checked rather than taken on trust: the io thread is `std::thread{ [&io] { io.run(); } }` with no catch, so an exception escaping a completion escapes the thread function and terminates the process. That is what the code comment now states.

The bound is the 25 MiB receive limit RFC 77 requires, which was a bare literal in `default_channel_arguments()` and is now the named `max_receive_message_size` both sites share — a second copy of the number would drift from the limit it is supposed to mean.

The test is `an_oversized_declared_length_is_refused`, and it is deliberately built from a *valid* frame just over the cap rather than a crafted header: a malformed header is refused with or without the bound, so the assertion would pass for the wrong reason. The corresponding mutation raises the bound out of reach and is killed.

### 4. `get_projected` neither negotiates compression nor decodes it

> `encode(get_projected_request)` does not call the read-compression helper that `encode(get_request)` uses, and the corresponding decode still reads `content_uncompressed` directly rather than going through `decode_content`.

Fixed: the projected read now negotiates compression and decodes through `decode_content` like every other read, and the `feature_not_available` refusal is gone from both the converter and the component.

The stated mechanism does not hold, though, and the reason to make the change is a different one.

> `GetRequest.compression` is `optional CompressionEnabled` whose zero value is `COMPRESSION_ENABLED_OPTIONAL`, so a gateway reading it with the plain value getter rather than a presence check sees `OPTIONAL` for an unset field and may return `content_compressed` anyway.

The reference gateway takes the field as a pointer and branches on presence, so an unset field is not read as `OPTIONAL`:

```go
func (h CompressHandler) MaybeCompressContent(
	in []byte, datatype memdx.DatatypeFlag, compressMode *kv_v1.CompressionEnabled,
) (bool, []byte, *status.Status) {
	if compressMode != nil {
		switch *compressMode {
		case kv_v1.CompressionEnabled_COMPRESSION_ENABLED_OPTIONAL:
```

With the field unset it takes the `else` branch and *uncompresses* before replying. So the previous code was not at risk of the finding-2 outcome on this path.

What justifies the change is the citation: projections and compression travel on the same `GetRequest`, and all three shipping SDKs put them there together — gocb has one `Get` carrying both `Project` and `Compression` and decompresses unconditionally (`kvprovider_ps.go:466-500`); the Java SDK sets compression before it adds the projections, on the same builder (`CoreProtostellarKeyValueRequests.java:99-105`); the .NET SDK sets `CompressionEnabled.Optional` on its projected read too (`StellarCollection.cs:205-231`). Refusing a compressed answer with `feature_not_available` made this the one read the client could not complete, and the gateway serves projections from its ordinary `Get` handler, so nothing about the path makes it unable to carry one.

### Two defects found while checking the above

**The user's compression setting never reached the transport.** `component_config` has carried a `compression` field, but the couchbase2 cluster built one with three initialisers for a four-field aggregate, so the fourth silently took the struct's own default. `cluster_options.enable_compression` — which the connection string and `compression().enabled(false)` both feed — was ignored, and every couchbase2 cluster compressed regardless. It is now mapped by a named helper beside `make_component_timeouts`, for the same reason that one exists.

**The ratio threshold was exclusive.** A value compressing to exactly `min_ratio` of its original was sent raw. All three references accept it, each by rejecting only a ratio strictly above the threshold: the Java SDK in `MemcacheProtocol.tryCompression`, the .NET SDK in `OperationCompressor.Compress`, gocb in `compressor.go`. The comparison is now `<=`. The size threshold needed no change — the Java and .NET SDKs both compress at `>= minSize`, as this does; gocb is the lone outlier with `> minSize`.

### Coverage

The unit suite gained boundary and per-path rows rather than more of the same: a value of exactly `min_size`, a ratio landing exactly on `min_ratio` (derived from the fixture's own compressed size over a power-of-two original, so the comparison is exact in binary floating point and can tell the inclusive bound from the exclusive one), an incompressible value that must go out raw, compression opt-in and decode on all four read paths, and the oversized frame above. The component suite gained `get_projected_negotiates_and_decodes_compression`, which asserts what left the client and what it made of the compressed reply on one call. Nine mutations across the two suites, all killed.

`live_kv.cxx` gained `compressed_values_round_trip_against_live_gateway`, and it was checked for falsifiability rather than assumed: truncating the frame the client sends makes a live gateway reject the write with `invalid_argument`, which is the property no in-process test can establish — that what the client produces is a snappy frame the gateway accepts and stores faithfully.

Two limits of that case are worth stating rather than leaving implied. Against a live gateway a read never came back on the compressed arm, including a read of a document the client had just stored compressed; both halves of the read-side decoding were confirmed unexercised live by breaking `decode_content` and watching the case still pass. Read-side decompression is therefore covered against an in-process server only. And the mapping from `cluster_options` into `component_config` — the defect above — has no test: it is reachable only by opening a cluster, and which arm of the oneof went out is not observable through any API a test can reach. The same is true of `make_component_timeouts` beside it.

File: core/protostellar/component.hxx [hunk 4]
```diff
@@ -111,6 +112,7 @@ struct component_config {
   std::shared_ptr<grpc::Channel> channel{};
   cluster_credentials credentials{};
   component_timeouts timeouts{};
+  kv::compression_settings compression{};
```
[the remark this answers is not in the document]
Comment (avsej) [reply core/protostellar/component.hxx:115]: The enabled flag is threaded at the head this review ran against. `cluster.cxx` builds the config with four fields, the fourth from a named helper beside `make_component_timeouts`:

```cpp
protostellar::component_config{ std::move(channel),
                                origin_.credentials(),
                                make_component_timeouts(options),
                                make_compression_settings(options) };
```

That was the same defect this comment describes — three initialisers for a four-field aggregate, so `compression` silently took the struct's own default and `enabled(false)` was ignored — and it is fixed in this push.

The thresholds are a separate matter and are deliberately left on the converter's defaults. They are dropped a layer higher than this file: `core::cluster_options` carries `enable_compression` and nothing else, and `public_cluster.cxx` maps only `opts.compression.enabled` into it, so `min_size`/`min_ratio` never reach core on any transport. Carrying them would be a change to the core options struct that the classic MCBP path shares, which is outside this ticket. The defaults here are the same 32 bytes and 0.83 the Java, .NET and Go SDKs use, so a caller who does not override them sees identical behaviour either way.

File: core/protostellar/kv_converter.cxx [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
```
[the remark this answers is not in the document]
Comment (avsej) [reply core/protostellar/kv_converter.cxx:65]: This is what the code at the head this review ran against already does — the declared length is parsed first, checked against the transport maximum, and only then decompressed:

```cpp
std::size_t length{};
if (!snappy::GetUncompressedLength(compressed.data(), compressed.size(), &length)) {
  return std::nullopt;
}
if (length > max_receive_message_size) {
  return std::nullopt;
}
std::string uncompressed;
if (snappy::Uncompress(compressed.data(), compressed.size(), &uncompressed)) {
```

`an_oversized_declared_length_is_refused` covers it, built from a valid frame just over the cap rather than a crafted header, since a malformed header is refused with or without the bound. No further change was made.

File: core/protostellar/component.hxx [hunk 6]
```diff
@@ -76,6 +76,7 @@
 #include "core/operations/management/search_index_get_documents_count.hxx"
 #include "core/operations/management/search_index_upsert.hxx"
 #include "core/protostellar/dispatcher.hxx"
+#include "core/protostellar/kv_converter.hxx"
```
Comment (DemetrisChr) [inline core/protostellar/component.hxx]: This will include the generated gRPC KV stubs, which violates the following which is mentioned below:
```
  // The generated gRPC stubs are held behind an opaque pointer so the generated protobuf and gRPC
  // surface stays out of every translation unit that includes this header -- none of it appears in
  // the interface, and the stub count grows with every service the transport learns to speak.
```

Perhaps we should move the `compression_settings` struct to this header file, to avoid the need for the `kv_converter.hxx` include?

File: core/protostellar/kv_converter.hxx [hunk 7]
```diff
@@ -139,25 +139,94 @@ to_core_token(const v1::MutationToken& token) -> couchbase::mutation_token
...
+// than inventing a value.
+template<typename Proto>
+inline auto
+decode_content(const Proto& proto) -> std::optional<std::vector<std::byte>>
+{
+  if (content_is_compressed(proto)) {
+    if (auto uncompressed = snappy_uncompress(proto.content_compressed())) {
+      return utils::to_binary(*uncompressed);
+    }
+    return std::nullopt;
```
Comment (DemetrisChr) [inline core/protostellar/kv_converter.hxx:211]: Should we log that there was an uncompression failure? Possibly at debug-level. Otherwise, the user only gets an `internal_server_failure` which might make it hard to debug if such an issue ever occurs.

File: core/cluster.cxx [hunk 8]
```diff
@@ -343,6 +343,15 @@ make_component_timeouts(const cluster_options& options) -> protostellar::compone
   timeouts.management = options.management_timeout;
   return timeouts;
 }
+
+// Core carries only the on/off switch, so min_size and min_ratio keep the converter's defaults.
```
Comment (DemetrisChr) [inline core/cluster.cxx]: This is true, but we do have them in the Public API's `compression_options`, so this will silently ignore `min_size` and `min_ratio`. Although, that issue currently exists in classic as well.

Should we pass them on to the core now, or do you prefer to handle that at a later stage across both protostellar and classic?

File: core/protostellar/kv_converter.hxx (hunk 7 above)
Comment (avsej) [reply core/protostellar/kv_converter.hxx:211]: Added `CB_LOG_DEBUG("failed to decompress snappy payload in response (compressed_size={})", proto.content_compressed().size());` inside `decode_content` when `snappy_uncompress` returns `std::nullopt`.

File: core/cluster.cxx (hunk 8 above)
Comment (avsej) [reply core/cluster.cxx]: Propagated `min_size` and `min_ratio` from `couchbase::compression_options` in `public_cluster.cxx` through `core::cluster_options` into `make_compression_settings`. Also decoupled `compression_settings` into `core/protostellar/compression_settings.hxx` so `component.hxx` stays isolated from Protobuf headers.

**Review by DemetrisChr — APPROVED** [review]
